_BASE_: "../Base.yaml"

DATASETS:
  TRAIN: ("ctw1500_poly_train_rotate_pos",)
  TEST: ("ctw1500_poly_test",)

MODEL:
  WEIGHTS: "ctw1500_final.pth" # or the provided pre-trained model
  TRANSFORMER:
    INFERENCE_TH_TEST: 0.41

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 2e-5
  LR_BACKBONE: 2e-6
  WARMUP_ITERS: 0
  STEPS: (9000,) # no step
  MAX_ITER: 13000
  CHECKPOINT_PERIOD: 1000

INPUT:
  MIN_SIZE_TEST: 1000 
  MAX_SIZE_TEST: 1280

TEST:
  EVAL_PERIOD: 1000
  USE_LEXICON: False
  LEXICON_TYPE: 1

OUTPUT_DIR: "output/Bridge/CTW1500/R_50_Polygon"
