_BASE_: "../Base-TESTR.yaml"

DATASETS:
  TRAIN: ("icdar2015_train",)
  TEST: ("icdar2015_test",)

MODEL:
  WEIGHTS: "icdar15_testr_R_50_polygon.pth"
  RESNETS:
    DEPTH: 50
  TRANSFORMER:
    NUM_FEATURE_LEVELS: 4
    INFERENCE_TH_TEST: 0.31
    ENC_LAYERS: 6
    DEC_LAYERS: 6
    DIM_FEEDFORWARD: 1024
    HIDDEN_DIM: 256
    DROPOUT: 0.1
    NHEADS: 8
    NUM_QUERIES: 100
    ENC_N_POINTS: 4
    DEC_N_POINTS: 4
    USE_POLYGON: True
    NUM_CTRL_POINTS: 16
    LOSS:
      POINT_TEXT_WEIGHT: 4.0
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 1e-5
  LR_BACKBONE: 1e-6
  WARMUP_ITERS: 0
  STEPS: (200000,)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 1000

TEST:
  USE_LEXICON: True
  LEXICON_TYPE: 3
  WEIGHTED_EDIT_DIST: True
  EVAL_PERIOD: 1000

INPUT:
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 1000, 1200, 1400)
  MAX_SIZE_TRAIN: 2333
  MIN_SIZE_TEST: 1440
  MAX_SIZE_TEST: 4000
OUTPUT_DIR: "output/Bridge/icdar15/R_50_Polygon"
